In [6]:

import numpy as np 


In [7]:
array = np.array([1,2,3]) 
print(array)

[1 2 3]


In [8]:
array2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(array2.shape) 

(15,)


In [9]:
a = array2.reshape(3,5) 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
print("shape: ",a.shape) 

print("dimension: ",a.ndim) 

print("data type: ",a.dtype.name) 

print("size: ",a.size) 
                       
print("type",type(a))  

shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type <class 'numpy.ndarray'>


In [14]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

In [15]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(array3.shape)

(3, 4)


In [17]:
zeros= np.zeros((3,4))

In [18]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.empty((4,5))

array([[ 1.33360450e+241,  7.03186965e-310,  1.71489145e-227,
         7.28577030e+199,  6.01124697e+175],
       [ 2.41695321e-311,  3.01526111e+150,  6.92684449e+218,
         3.75597342e+199,  1.36621083e+161],
       [ 6.18952898e+223,  3.51214546e+151, -9.25672125e+061,
         1.86345477e-303,  8.55292466e-310],
       [-8.61131834e+199,  4.72153766e+257,  1.62229162e+243,
         1.78421650e-309,  6.32306726e+233]])

In [22]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
print(b[1,1]) 

print(b[:,1]) 

print(b[1,:]) 

print(b[1,1:4])

print(b[-1,:]) 
print(b[:,-1]) 

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [26]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
